CREATE TABLE SOLD(
SOLDSEQ VARCHAR2(20) PRIMARY KEY,
CUSTOMERID VARCHAR2(20) CONSTRAINT CUSTOMER_CUSTOMERID_FK REFERENCES CUSTOMER,
PRODUCTSEQ VARCHAR2(20) CONSTRAINT PRODUCT_PRODUCTSEQ_FK REFERENCES PRODUCT,
INDATE DATE,
QUANTITY NUMBER)

CREATE TABLE CUSTOMER(
CUSTOMERID VARCHAR2(20) PRIMARY KEY,
CUSTOMERPW VARCHAR2(20),
NAME VARCHAR2(20),
PHONE VARCHAR2(20),
BIRTHDATE VARCHAR2(20),
ADDRESS VARCHAR2(20),
INDATE DATE)

CREATE TABLE PRODUCT(
PRODUCTEQ VARCHAR2(20) PRIMARY KEY,
NAME VARCHAR2(20),
QUANTITY NUMBER(20),
PRICE NUMBER(20),
COMMENTS VARCHAR2(20),
INDATE DATE)

CREATE TABLE ADMINS(
ADMINID VARCHAR2(20) PRIMARY KEY,
ADMINPW VARCHAR2(20))
